name: build

on:
  push:
    branches:
      - master
#    paths:
#      - '!*.rst'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python setup.py install
      - name: pytest and coverage
        run: |
          python -m pip install --upgrade pip
          pip install pytest-pep8
          pip install pytest-cov==2.5.0
      - name: Upload coverage to codeclimate
        uses: paambaati/codeclimate-action@v2.5.6
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: py.test aoc --doctest-modules --pep8 aoc -v --cov aoc --cov-report xml
          coverageLocations:
            "${{github.workspace}}/coverage.xml:coverage.py"
      - name: Create distribution
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@37e305e7413032d8422456179fee28fac7d25187
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish distribution 📦 to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@37e305e7413032d8422456179fee28fac7d25187
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}