name: Upload Python Package to Test pypi

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
          draft: true
          prerelease: false
  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          python setup.py sdist bdist_wheel
          git status
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@37e305e7413032d8422456179fee28fac7d25187
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
#      - name: Publish distribution 📦 to PyPI
#        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
#        uses: pypa/gh-action-pypi-publish@37e305e7413032d8422456179fee28fac7d25187
#        with:
#          user: __token__
#          password: ${{ secrets.pypi_password }}